# Azure DevOps pipeline for Azure deployment

variables:
- group: newone-key-vault

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - backend

stages:
- stage: Validate
  displayName: Validate
  jobs:
  - job: validate
    pool:
      vmImage: ubuntu-latest
    steps:
    # Install Checkov
    - bash: pip3 install checkov
      displayName: 'Install checkov'
      name: 'install_checkov'

    # Azure key-new-one Vault
    # Download Azure key-new-one Vault secrets
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'newoneKeyvault'
        KeyVaultName: 'newonekeyvault'
        SecretsFilter: '*'
        RunAsPreJob: false
    
    # Init
    - task: TerraformTaskV2@2
      displayName: Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/backend'
        backendServiceArm: 'newoneKeyvault'
        backendAzureRmResourceGroupName: 'newone'
        backendAzureRmStorageAccountName: 'newonestgs'
        backendAzureRmContainerName: 'terraform-states'
        backendAzureRmKey: 'tf/terraform.tfstate'

  # Validate
    - task: TerraformCLI@0
      displayName: Validate Config
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/backend'

  # Verify module files with Checkov
    - bash: checkov --directory $(System.DefaultWorkingDirectory)/backend/.terraform --skip-check CKV_DOCKER_* -o junitxml > $(System.DefaultWorkingDirectory)/Checkov-Module-Report.xml
      displayName: 'Verify modules with Checkov'
      name: 'checkov_module_check'

  # Publish test results for modules
  # Shout out to Adin Ermie for this one! https://adinermie.com/publishing-checkov-terraform-quality-checks-to-azure-devops-pipelines/
    - task: PublishTestResults@2
      displayName: Publish Checkov Module Test Results
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/*Checkov-Module-Report.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)'
        mergeTestResults: false
        testRunTitle: Checkov Module Scan
        failTaskOnFailedTests: false
        publishRunAttachments: true

  # Verify main files with Checkov
    - bash: checkov --directory $(System.DefaultWorkingDirectory)/backend -o junitxml > $(System.DefaultWorkingDirectory)/Checkov-Root-Report.xml
      displayName: 'Verify root module with Checkov'
      name: 'checkov_root_check'

  # Publish test results for root module
    - task: PublishTestResults@2
      displayName: Publish Checkov Root Test Results
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/*Checkov-Root-Report.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)'
        mergeTestResults: false
        testRunTitle: Checkov Root Scan
        failTaskOnFailedTests: false
        publishRunAttachments: true
    
- stage: Plan
  displayName: Plan
  jobs:
  - job: plan
    pool:
      vmImage: ubuntu-latest
    steps:
    # Install Checkov
    - bash: pip3 install checkov
      displayName: 'Install checkov'
      name: 'install_checkov'

    # Azure key-new-one Vault
    # Download Azure key-new-one Vault secrets
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'newoneKeyvault'
        KeyVaultName: 'newonekeyvault'
        SecretsFilter: '*'
        RunAsPreJob: false
  
    # Init
    - task: TerraformTaskV2@2
      displayName: Validate Config
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/backend'
        backendServiceArm: 'newoneKeyvault'
        backendAzureRmResourceGroupName: 'newone'
        backendAzureRmStorageAccountName: 'newonestgs'
        backendAzureRmContainerName: 'terraform-states'
        backendAzureRmKey: 'tf/terraform.tfstate'

  # Plan
    - task: TerraformTaskV2@2
      displayName: Validate Config
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/backend'
        backendServiceArm: 'newoneKeyvault'
        backendAzureRmResourceGroupName: 'newone'
        backendAzureRmStorageAccountName: 'newonestgs'
        backendAzureRmContainerName: 'terraform-states'
        backendAzureRmKey: 'tf/terraform.tfstate'

  # Plan
    - task: TerraformCLI@0
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/backend'
        environmentServiceName: 'newoneKeyvault'
        commandOptions: '-out=$(System.DefaultWorkingDirectory)/backend/main.tfplan'
        allowTelemetryCollection: true
        publishPlanResults: 'Terraform Plan'



  # Verify plan with Checkov
    - bash: |
        cd $(System.DefaultWorkingDirectory)/backend
        ls
        terraform show -json main.tfplan > $(System.DefaultWorkingDirectory)/main.json
        checkov -f $(System.DefaultWorkingDirectory)/main.json -o junitxml > $(System.DefaultWorkingDirectory)/Checkov-Plan-Report.xml
      displayName: 'Verify plan with Checkov'
      name: 'checkov_plan_check'
  # Publish test results for plan
    - task: PublishTestResults@2
      displayName: Publish Checkov Plan Test Results
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/*Checkov-Plan-Report.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)'
        mergeTestResults: false
        testRunTitle: Checkov Plan Scan
        failTaskOnFailedTests: false
        publishRunAttachments: true

# Approve
- stage: Approve
  displayName: Approve
  jobs:
  - job: approve
    displayName: Wait for approval
    pool: server
    steps: 
    - task: ManualValidation@0
      timeoutInMinutes: 60
      inputs:
        notifyUsers: 'rafa.v_s@hotmail.com'
        instructions: 'Review the plan in the next hour'

- stage: Apply
  displayName: Apply
  jobs:
  - job: apply
    pool:
      vmImage: ubuntu-latest
    steps:

    # Azure key-new-one Vault
    # Download Azure key-new-one Vault secrets
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'newoneKeyvault'
        KeyVaultName: 'newonekeyvault'
        SecretsFilter: '*'
        RunAsPreJob: false

  # Init
    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/backend'
        backendServiceArm: 'newoneKeyvault'
        backendAzureRmResourceGroupName: 'newone'
        backendAzureRmStorageAccountName: 'newonestgs'
        backendAzureRmContainerName: 'terraform-states'
        backendAzureRmKey: 'tf/terraform.tfstate'

  # Apply
    - task: TerraformCLI@0
      displayName: Apply Terraform Deployment
      env:
        ARM_SAS_TOKEN: $(sas-key)
        ARM_CLIENT_ID: $(app-id)
        ARM_CLIENT_SECRET: $(password-sp)
        ARM_SUBSCRIPTION_ID: $(sb-id)
        ARM_TENANT_ID: $(tenant-id)
      inputs:
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/backend'
        commandOptions: '-auto-approve'